### Prueba de POST a /api/test
POST http://localhost:3000/api/test
Content-Type: application/json

{
  "id": 123,
  "title": "Hola Next.js",
  "tags": ["api", "test", "nextjs"],
  "author": {
    "name": "Esteban",
    "role": "dev"
  }
}


### Prueba de conexión a Supabase
GET http://localhost:3000/api/test-supabase


### Listar archivos dentro de una carpeta
GET http://localhost:3000/api/current-data/listContent

### Listar contenido de la carpeta "PersonajesData"
GET http://localhost:3000/api/current-data/listContent?path=PersonajesData